version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-jwt
    environment:
      POSTGRES_DB: jwt_db
      POSTGRES_USER: jwt_user
      POSTGRES_PASSWORD: jwt_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
